#!/usr/bin/env bash
# Provide lambdas completions
# Usage: lambdas test [lambda]
# Summary: Run tests for the lambda
#
# Example:
#   lambdas generate-csr iot BedroomLamp

set -eo pipefail

lambda=$1
shift
docker-compose run --rm -w /lambdas/${lambda} lambdas bash -c "yarn $*"
