---
Parameters:
  HVACCertificateSigningRequest:
    Type: String
    Description: Certificate Signing Request for the HVAC
    Default: |
      -----BEGIN CERTIFICATE REQUEST-----
      MIICzjCCAbYCAQAwgYgxCzAJBgNVBAYTAkFVMREwDwYDVQQIDAhWaWN0b3JpYTES
      MBAGA1UEBwwJTWVsYm91cm5lMR0wGwYDVQQKDBRNYWRQaWxvdCBQcm9kdWN0aW9u
      czENMAsGA1UEAwwESFZBQzEkMCIGCSqGSIb3DQEJARYVbXlsZXNAbWFkcGlsb3Qu
      Y29tLmF1MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq3ezE4ezToe3
      ES/zVPJ6xSeqVV5OpeM2muuwJUcdJs+pUoA3GIYIL9ofA57ZVbDillqVT8EmWqa7
      dFMUFJ2xymN1V/tfdwAjzOIOfp/wZKujb2V1YaCxB/QuiSKZvbEA6tZGtouI4Szi
      plwAeDbsJyK2+odQzAQIotEMJ2Ut+QnyzInE9+vCt8hoFZqW/immDbUiJWUFc1k1
      +lmEUP6dHRWX75qnwx08i7Cmg+KMga/W+edNizt31CrLNq5A5XMSlRCnQziiQyj6
      6dHqEMlQFtDiC8Pnwcs1M7gOdX+T/VATFUrzwMucMz1rRrX3ozm48zJIQGpLyB4k
      jsMv/PMldQIDAQABoAAwDQYJKoZIhvcNAQELBQADggEBAGZHNizQjRFiZuPNs3vT
      GONvKoa08XTQ7Qdi0XDtpimTAkAFJhgGELVFYpK0N/jnf9eOcgXHi2NTjWs6SjeZ
      C3TqvfcsB2QKfxFFTA6h/5YbSpCgEvl+y8OaCqgW63qKqBmL+SgzLTEd68IRraOp
      iVUATtSMOkfQviIRMdGpmq/HygWzGN26gGHWNs74dqz7IzNeDhp/Yr3dnxxYq/8L
      RClxVInX93/v8UYoiaB1b3ntDVGkRKIKgz6Kgyzr1PNEmXZOiTCWxs1XPNpJwrWv
      F7DZrN1gmFLK3B3Ou+kCa+T63tPSDzxidE/G0G25KyQf2JcQ0EDMDpmWyKhBP7mL
      4IM=
      -----END CERTIFICATE REQUEST-----


Resources:
  HVACPublishPolicy:
    Type: "AWS::IoT::Policy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Action:
            - "iot:Publish"
            - "iot:UpdateThingShadow"
            - "iot:DeleteThingShadow"
          Resource:
            - arn:$(AWS::Partition):iot:$(AWS::Region):$(AWS::AccountId):topic/\$aws/things/iot-HVAC/shadow/update
            - arn:$(AWS::Partition):iot:$(AWS::Region):$(AWS::AccountId):topic/\$aws/things/iot-HVAC/shadow/delete

  HVACSubscribePolicy:
    Type: "AWS::IoT::Policy"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: "Allow"
          Action:
            - "iot:Subscribe"
            - "iot:Receive"
            - "iot:GetThingShadow"
          Resource:
            - arn:$(AWS::Partition):iot:$(AWS::Region):$(AWS::AccountId):topicfilter/\$aws/things/iot-HVAC/shadow/update
            - arn:$(AWS::Partition):iot:$(AWS::Region):$(AWS::AccountId):topicfilter/\$aws/things/iot-HVAC/shadow/delete
            - arn:$(AWS::Partition):iot:$(AWS::Region):$(AWS::AccountId):topicfilter/\$aws/things/iot-HVAC/shadow/update/accepted
            - arn:$(AWS::Partition):iot:$(AWS::Region):$(AWS::AccountId):topicfilter/\$aws/things/iot-HVAC/shadow/update/rejected
            - arn:$(AWS::Partition):iot:$(AWS::Region):$(AWS::AccountId):topicfilter/\$aws/things/iot-HVAC/shadow/delete/accepted
            - arn:$(AWS::Partition):iot:$(AWS::Region):$(AWS::AccountId):topicfilter/\$aws/things/iot-HVAC/shadow/delete/rejected

  HVACCertificate:
    Type: "AWS::IoT::Certificate"
    Properties:
      CertificateSigningRequest: $(HVACCertificateSigningRequest)
      Status: ACTIVE

  HVACCertificateAttach:
    Type: "AWS::IoT::ThingPrincipalAttachment"
    Properties:
      ThingName: $(HVAC)
      Principal: arn:$(AWS::Partition):iot:$(AWS::Region):$(AWS::AccountId):cert/$(HVACCertificate)

  HVACConnectPolicyAttach:
    Type: "AWS::IoT::PolicyPrincipalAttachment"
    Properties:
      PolicyName: $(ConnectPolicy)
      Principal: arn:$(AWS::Partition):iot:$(AWS::Region):$(AWS::AccountId):cert/$(HVACCertificate)

  HVACPublishPolicyAttach:
    Type: "AWS::IoT::PolicyPrincipalAttachment"
    Properties:
      PolicyName: $(HVACPublishPolicy)
      Principal: arn:$(AWS::Partition):iot:$(AWS::Region):$(AWS::AccountId):cert/$(HVACCertificate)

  HVACSubscribePolicyAttach:
    Type: "AWS::IoT::PolicyPrincipalAttachment"
    Properties:
      PolicyName: $(HVACSubscribePolicy)
      Principal: arn:$(AWS::Partition):iot:$(AWS::Region):$(AWS::AccountId):cert/$(HVACCertificate)
