---
version: '2'

services:
  infrastructure:
    build:
      context: infrastructure/.
      dockerfile: Dockerfile
    image: iot-test/infrastructure
    volumes:
      - ./infrastructure:/tools/
      - ./certificates:/certificates
      - $HOME/.aws:/root/.aws:ro
    tmpfs:
      - /tmp
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION:

  mosquitto-client:
    build:
      context: mosquitto-client/.
      dockerfile: Dockerfile
    image: iot-test/mosquitto-client
    volumes:
      - ./certificates:/certificates
      - $HOME/.aws:/root/.aws:ro
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION:

  lambdas:
    build:
      context: lambdas/.
      dockerfile: Dockerfile
    image: iot-test/lambdas
    volumes:
      - ./lambdas:/lambdas

  temperature-sensor:
    build:
      context: temperature-sensor/.
      dockerfile: Dockerfile
    image: iot-test/temperature-sensor
    volumes:
      - ./temperature-sensor:/app
      - ./certificates:/certificates
      - $HOME/.aws:/root/.aws:ro
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION:
