Resources:
  SetHVACModeExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: "logs:*"
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action: "iot:UpdateThingShadow"
            Resource: arn:$(AWS::Partition):iot:$(AWS::Region):$(AWS::AccountId):thing/iot-HVAC

  SetHVACMode:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: /lambdas/setHVACMode/build/dist.zip
      Description: Sets the HVAC mode, and turns on the fan when required
      Handler: index.setHVACMode
      MemorySize: 128
      Role: arn:aws:iam::$(AWS::AccountId):role/$(SetHVACModeExecutionRole)
      Runtime: nodejs6.10
      Timeout: 90
      Environment:
        Variables:
          ENDPOINT: a1sjiazdf7qxjd.iot.ap-southeast-2.amazonaws.com
          TOPIC: arn:$(AWS::Partition):iot:$(AWS::Region):$(AWS::AccountId):topic/\$aws/things/iot-HVAC/shadow/update
