#!/usr/bin/env bash
# Generate and download a certificate for a thing
# Usage: infrastructure certificate [thing]
# Summary: Manage Cloudformation stacks
#
# Example:
#   infrastructure generate-certificate BedroomLamp

set -eo pipefail

docker-compose run --rm infrastructure bash -c "/tools/bin/generate-certificate ${@:1}"
