#!/usr/bin/env bash
# Provide infrastructure completions
# Usage: infrastructure generate-csr [stack] [thing]
# Summary: Generate csr for a thing
#
# Example:
#   infrastructure generate-csr iot BedroomLamp

set -eo pipefail

docker-compose run --rm infrastructure bash -c "/tools/bin/generate-csr ${1} ${2}"
