#!/usr/bin/env bash
# Provide infrastructure completions
# Usage: infrastructure stack [application] [action] [stack-name]
# Summary: Manage Cloudformation stacks
# Help:
#   Applications:
#   - base
#
# Example:
#   infrastructure stack update base development

set -eo pipefail

case "$1" in
  --complete)
    echo create
    echo update
    echo diff
  ;;
  create)
    docker-compose run --rm -w "/tools/$2/cloudformation" infrastructure_tools bash -c "/tools/bin/create-stack ${@:3}"
  ;;
  update)
    docker-compose run --rm -w "/tools/$2/cloudformation" infrastructure_tools bash -c "/tools/bin/update-stack ${@:3}"
  ;;
  diff)
    docker-compose run --rm -w "/tools/$2/cloudformation" infrastructure_tools bash -c "/tools/bin/diff-stack ${@:3}"
  ;;
  *)
    infrastructure help stack
  ;;
esac
