#!/usr/bin/env bash
# Provide infrastructure completions
# Usage: infrastructure stack [application] [action] [stack-name]
# Summary: Manage Cloudformation stacks
#
# Example:
#   infrastructure stack update iot

set -eo pipefail

case "$1" in
  --complete)
    echo create
    echo update
    echo diff
  ;;
  create)
    docker-compose run --rm -w "/tools/app/cloudformation" infrastructure bash -c "/tools/bin/create-stack ${@:2}"
  ;;
  update)
    docker-compose run --rm -w "/tools/app/cloudformation" infrastructure bash -c "/tools/bin/update-stack ${@:2}"
  ;;
  diff)
    docker-compose run --rm -w "/tools/app/cloudformation" infrastructure bash -c "/tools/bin/diff-stack ${@:2}"
  ;;
  delete)
    docker-compose run --rm -w "/tools/app/cloudformation" infrastructure bash -c "/tools/bin/deleted-stack ${@:2}"
  *)
    infrastructure help stack
  ;;
esac
