#!/usr/bin/env bash
# Generate csr for a thing
# Usage: infrastructure certificate [thing]
#
# Example:
#   infrastructure generate-csr BedroomLamp

set -eo pipefail

docker-compose run --rm infrastructure bash -c "/tools/bin/generate-csr ${@:1}"
